# This is a basic workflow to help you get started with Actions

name: deploy surge automatically

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Intall NodeJs
        uses: action/setup-node@v2-beta
        with:
          node version: 12

      # Runs a set of commands using the runners shell
      - name: Install Surge
        run: npm install-g surge
        
      #Run surge on deploy
      - name: Run Surge
        run: Surge./Project1.surge.sh --token ${{secrets.SURGE_PROJECT1}}
          
          echo Add other actions to build,
          echo test, and deploy your project.
